### ISSUE TITLE
Darc can postpone destruction of the pointer for arbitrary long time

### ISSUE THREAD

**Issue by vorner** [brunoczim/lockfree#2]
The incinerator tries to delete the data inside `swap` and similar methods. But if there's a concurrent `load`, it just stores the `Arc` until next time. But the next time does not have to come in the current thread, or the next `swap` might also be blocked, etc. So the `Arc` might stay there for a very long time.

This is probably a valid design choice, but it is not clear from the documentation and one would not expect that. If I store a large data at the end of the `Arc` and exchange it from time to time for a new instance, I expect the old ones to disappear once they are no longer there. In this way, it can effectively eat a lot of RAM. So it would be great if the docs made it clear.

**Comment by brunoczim** [comment]
Well, I am indeed interested in improving the `incinerator` algorithm, but the current implementation is the only lock-free way I found. I mean, [even ticki used some Mutexes](https://github.com/redox-os/tfs/blob/master/conc/src/global.rs) to implement Hazard Pointers.

But yes, I believe I should point out some things on the docs. Some of them are:
1. Whenever a thread exits, all its garbage is dropped (if OS's thread state implementation is not buggy)
2. Your application could call `incinerator::try_force` after exiting a concurrent context, in order to clean main thread's garbage, or periodically in the concurrent context.

PS: Sorry for taking so long, I moved the project to gitlab :P

**Comment by brunoczim** [comment]
I have actually found a way of postponing the deletion only until the deletion of Darc itself (or anything else we would apply this postponing). It is a per-object incinerator. However, there are some problems:

1. It has a worse performance.
2. Lifetimes might get a little cumbersome.

**Comment by vorner** [comment]
I'm not 100% sure that's a big improvement. I mean, it's still unusable for any kind of RAII-style things. Also, in the design pattern you have one Darc for some global data structure, it never gets dropped anyway.

Anyway, I don't think this is actually a *performance* issue. It is a design limitation, which is fine, but the user needs to be aware of it. So I think it is more like a documentation thing.

**Comment by brunoczim** [comment]
I know it is not really about performance. 

My point is: a per-object incinerator softens problem of post-poning the drop for indefinite time (not only for Arc, but for any structure). However, it has a performance impact :(

I actually updated the docs for incinerator itself (but not for each structure).

I am still working on a way of improving this style of incinerator because I do want to overcome the design limitation without too much impact on performance.

**Comment by brunoczim** [comment]
Well, I ended up removing `Darc`. I did not show up as a good trade-off. Its performance was not that good compared to mutexed structures and most places where it could be used weren't using it.

However, for other structures, I actually implemented a per-object incinerator, which softens the memory-usage impact of postponing deletion. You might still have some problems with structures stored in static variables, but I think it is ok.

I am closing this since I changed the incinerator implementation and I removed `Darc`.
